apiVersion: v1
entries:
  nginx:
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2022-06-22T22:43:23.420915204Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: NGINX Open Source is a web server that can be also used as a reverse
      proxy, load balancer, and HTTP cache. Recommended for high-demanding sites due
      to its ability to provide faster content.
    digest: sha256:5e7dfc91b89cc7c9e49ca638ce566399a6b05b9a5e1e38d0da88e707648a9c14
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: nginx
    urls:
    - nginx-12.0.5.tgz
    version: 12.0.5

