apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  configManagementPlugins: |-
    - name: argocd-test-plugin
      generate:
        command: ["/tmp/argocd-xfers-plugin"]
