apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  configManagementPlugins: |-
    - name: argocd-test-plugin
      generate:
        command: ["/tmp/argocd-xfers-plugin"]
    - name: argocd-helm-ext-plugin
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["/tmp/argocd-helm-ext-plugin"]
        args: ["--include-crds"]
