apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-helm-ext-plugin-patch
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
          - name: custom-tools
            mountPath: /usr/local/bin/argocd-helm-ext-plugin
            subPath: argocd-helm-ext-plugin

      initContainers:
      - name: download-tools
        image: alpine:3.8
        imagePullPolicy: IfNotPresent
        command: [sh, -c]
        env:
          - name: APP_VERSION
            value: "v1.0.0"
        args:
          - >-
            wget -O argocd-helm-ext-plugin
            https://github.com/Xfers/argocd-helm-ext-plugin/raw/${APP_VERSION}/release/argocd-helm-ext-plugin &&
            chmod +x argocd-helm-ext-plugin&&
            mv argocd-helm-ext-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      volumes:
        - name: custom-tools
          emptyDir: {}
