apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: ["/usr/local/bin/argocd-lovely-plugin"]
      discover:
        fileName: "./*.yaml"
      allowConcurrency: true
      lockRepo: false