apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  configManagementPlugins: |-
    - name: argocd-lovely-plugin
      generate:
        command: ["/usr/local/bin/argocd-lovely-plugin"]
    - name: argocd-test-plugin
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME . --install-crds | /tmp/argocd-xfers-plugin"]
