apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  configManagementPlugins: |-
    - name: argocd-helm-ext-plugin
      generate:
        command: ["argocd-helm-ext-plugin"]
        args: ["--include-crds"]
