apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/arloliu/argocd-demo.git
    targetRevision: HEAD
    path: apps/demo-app
    plugin:
      name: argocd-test-plugin
      env:
        - name: HELM_REPO_URL
          value: http://helm-repo.local/charts/packages
        - name: HELM_CHART
          value: nginx
        - name: HELM_CHART_VERSION
          value: "12.0.5"
        - name: HELM_CUSTOM_VALUE_FILES
          value: values.yaml secrets.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
