apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/arloliu/argocd-demo.git
    targetRevision: HEAD
    path: apps/demo-app
    plugin:
      name: argocd-test-plugin
      env:
        - name: HELM_CHART_VERSION
          value: "0.3.0"

  destination:
    server: https://kubernetes.default.svc
    namespace: default
