apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/arloliu/argocd-demo/main/apps
    targetRevision: 12.0.5
    chart: nginx
    plugin:
      name: argocd-test-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
