apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/arloliu/argocd-demo/main
    path: apps/charts/packages
    targetRevision: 12.0.5
    chart: nginx
    helm:
      releaseName: "test"
      valueFiles:
      - ../../demo-app/values.yaml
    # plugin:
    #   name: argocd-lovely-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
